prob1 :	prob1.cpp seqLinearList.hpp seqLinearList.cpp sorting.hpp sorting.cpp
					g++ -o prob1 prob1.cpp
prob3:	prob3.cpp seqLinearList.hpp seqLinearList.cpp sorting.hpp sorting.cpp
					g++ -o prob3 prob3.cpp
prob4:	prob4.cpp seqLinearList.hpp seqLinearList.cpp sorting.hpp sorting.cpp
					g++ -o prob4 prob4.cpp
sortMain: sortmain.cpp seqLinearList.hpp seqLinearList.cpp sorting.hpp sorting.cpp
					g++ -o sortMain sortMain.cpp
clean :
					rm prob1 prob3 prob4 sortMain
