prob4 :	prob4.cpp prob3 prob2 prob1 AbstractGraph.hpp AdjacencyList.hpp AdjacencyMatrix.hpp DirectedGraph.hpp GraphAdjacencyBase.hpp seqLinearList.cpp seqLinearList.hpp helper.hpp
					g++ -o prob4 prob4.cpp
prob3 :	prob3.cpp helper.hpp AVL.hpp BSTree.hpp BinaryTree.hpp
					g++ -o prob3 prob3.cpp
prob2:	prob2.cpp AbstractGraph.hpp AdjacencyList.hpp AdjacencyMatrix.hpp UndirectedGraph.hpp GraphAdjacencyBase.hpp seqLinearList.cpp seqLinearList.hpp helper.hpp
					g++ -o prob2 prob2.cpp
prob1:	prob1.cpp helper.hpp
					g++ -o prob1 prob1.cpp
clean :
					rm prob1 prob2 prob3 prob4
